services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8079:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8079
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HTTP_RELATIVE_PATH: /
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: debug                # more visibility while debugging

    command: start-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./keycloak-theme/ssl-theme:/opt/keycloak/themes/ssl-theme