server:
  port: 8085

spring:
  application:
    name: vente-service

  datasource:
    url: jdbc:postgresql://localhost:5432/vente_db
    username: postgres
    password: "postgres"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

commandeservice:
  url: http://localhost:8081

comptabiliteservice:
  url: http://localhost:8082

livraisonservice:
  url: http://localhost:8083

stockservice:
  url: http://localhost:8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address:-localhost}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      zone: primary

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: INFO
    org.example.stockservice: DEBUG
    org.springframework.cloud: INFO
    org.springframework.web: INFO